"""
Django settings for hello project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# import logging.handlers
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$a$14$tsmey#2s$aq72s(32el*p$*nni7i5zva+t0f6i)vw&v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.localhost', '127.0.0.1', '[::1]'] #[]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # 'hello.middlewaretracing.OpenTelemetryMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hello.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hello.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "DEBUG") # CRITICAL, ERROR, WARNING, INFO, DEBUG
OTEL_LOG_LEVEL = os.getenv("OTEL_LOG_LEVEL") # CRITICAL, ERROR, WARNING, INFO, DEBUG

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": DEFAULT_LOG_LEVEL,
            "class": "logging.StreamHandler",
        },
        "django.server": {
            "level": DEFAULT_LOG_LEVEL,
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console", "otlp"],
        "level": DEFAULT_LOG_LEVEL,
    },
    "loggers": {
        # "": {
        #     "handlers": ["console"],
        #     "level": "INFO",
        # },
        "django": {
            "handlers": ["console", "otlp"],
            "level": DEFAULT_LOG_LEVEL,
        },
        "django.server": {
            "handlers": ["otlp"], #"django.server"],
            "level": DEFAULT_LOG_LEVEL,
            "propagate": False,
        },
    },
}

if os.getenv('OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED'):
    # Here we have some choses
    # 1. If have your standard Django loging is configured you can rest to Django defaults with:
    #    LOGGING = None
    #    That seams to send some django.server logs to the stderr!
    # 2. If have your standard Django loging is configured you can disable Django for logging setup with:
    LOGGING_CONFIG = None
    # 3. Manually set up the your OpenTelementry logging configuration yourself, which kind of pain.

    
    if os.getenv("OTEL_LOGS_EXPORTER") == "console,otlp":
        print(f"setings1 - OTEL_LOGS_EXPORTER: {os.getenv("OTEL_LOGS_EXPORTER")}")
        # set OTEL writes only to otel exporter 
        # os.environ["OTEL_LOGS_EXPORTER"] = "otlp"
        # print("setings2 - OTEL_LOGS_EXPORTER: "+ os.getenv("OTEL_LOGS_EXPORTER"))

    if OTEL_LOG_LEVEL:
        import logging
        #     # logging.basicConfig()
        #     logging.root.setLevel(level=logging.NOTSET) # level=logging.NOTSET
        #     # logging.basicConfig(level=logging.NOTSET) # level=logging.NOTSET
        #     # logging.getLogger().setLevel(OTEL_LOG_LEVEL)
        print(f"print - OTEL root getEffectiveLevel: {logging.root.getEffectiveLevel()}")
        logging.info(f"Settings2 - OTEL root getEffectiveLevel: {logging.root.getEffectiveLevel()}")
        logging.root.setLevel(OTEL_LOG_LEVEL)
        logging.info(f"Settings3 - OTEL root getEffectiveLevel: {logging.root.getEffectiveLevel()}")
        logging.info(f"Settings4 - OTEL Log Level: {OTEL_LOG_LEVEL}")
        # logging.getLogger("django.server").setLevel(logging.NOTSET)